version: "3"
services:
  openxeco-api:
    image: "openxeco-api:latest"
    restart: always
    ports:
      - "5002:5002"
    environment:
      DEBUG: "true"
      JWT_SECRET_KEY: "some_random_secret"
      OPENXECO_API_ENDPOINT: "http://localhost:5000/"
      ECCC_API_ENDPOINT: ""
      ECCC_API_KEY: ""